### PR TITLE
Profiles

### PR DESCRIPTION
**Pull request by gopenshaw**
Profiles and posts are signed with private key and then encrypted with group key. I put that logic into an `SymmetricEncryptedData`.

### CODE REVIEW

**Comment by isdavid** [comment]
What shows up for the profile user name when you run it on your device? Mine shows "ProfileActivity". It seems that
`getSupportActionBar().setTitle(mProfileUsername);`
being called outside of onCreate doesn't allow it to set for whatever reason.

**Comment by isdavid** [comment]
Also the default about me shouldn't be "I'm a newb" haha. Just leave it blank.

**Comment by isdavid** [comment]
I found the fix for the user name and deleted "I'm a newb"

**Comment by gopenshaw** [comment]
Awesome, thanks!

**Comment by isdavid** [comment]
Everything else looks good. Time to mmmmmmmmmeeeeeeeeeeerrrrrrrgggggggggggeeeeeeeeeee

**Pull request merged**
